version: '3.8'

services:
    app:
        container_name: cobalt-playlist-downloader
        build:
            context: .
        ports:
            - "5001:5000"
        volumes:
            - .:/app
